// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Simply_Beautify_CSharp
{
    internal sealed partial class Vsix
    {
        public const string Id = "Simply_Beautify_CSharp.2fc33670-6a0d-4a6f-8c16-e6096da51116";
        public const string Name = "Simply_Beautify_CSharp";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Parminder Singh";
        public const string Tags = "";
    }
}
